### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ghost** [UnknownOre/EnchantShopUI#14] opened 2019-03-30 15:50 UTC
On execute command /eshop

[11:46:36] [Server thread/CRITICAL]: Error: "Class 'UnknownOre\EnchantUI\libs\jojoe77777\FormAPI\SimpleForm' not found" (EXCEPTION) in "plugins/EnchantUI/src/UnknownOre/EnchantUI/Main" at line 69
[11:46:36] [Server thread/DEBUG]: #0 plugins/EnchantUI/src/UnknownOre/EnchantUI/Commands/ShopCommand(42): UnknownOre\EnchantUI\Main->listForm(pocketmine\Player object)
[11:46:36] [Server thread/DEBUG]: #1 src/pocketmine/command/SimpleCommandMap(270): UnknownOre\EnchantUI\Commands\ShopCommand->execute(pocketmine\Player object, string eshop, array Array())
[11:46:36] [Server thread/DEBUG]: #2 src/pocketmine/Server(2010): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string eshop)
[11:46:36] [Server thread/DEBUG]: #3 src/pocketmine/Player(2221): pocketmine\Server->dispatchCommand(pocketmine\Player object, string eshop)
[11:46:36] [Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(239): pocketmine\Player->chat(string /eshop)
[11:46:36] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
[11:46:36] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[11:46:36] [Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/protocol/BatchPacket(119): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
[11:46:36] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[11:46:36] [Server thread/DEBUG]: #9 src/pocketmine/Player(3114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[11:46:36] [Server thread/DEBUG]: #10 src/pocketmine/network/mcpe/RakLibInterface(170): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[11:46:36] [Server thread/DEBUG]: #11 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 86.247.250.148 57716, raklib\protocol\EncapsulatedPacket object, integer 0)
[11:46:36] [Server thread/DEBUG]: #12 src/pocketmine/network/mcpe/RakLibInterface(110): raklib\server\ServerHandler->handlePacket()
[11:46:36] [Server thread/DEBUG]: #13 src/pocketmine/network/mcpe/RakLibInterface(100): pocketmine\network\mcpe\RakLibInterface->process()
[11:46:36] [Server thread/DEBUG]: #14 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[11:46:36] [Server thread/DEBUG]: #15 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
[11:46:36] [Server thread/DEBUG]: #16 src/pocketmine/Server(2328): pocketmine\snooze\SleeperHandler->sleepUntil(double 1553960796.2503)
[11:46:36] [Server thread/DEBUG]: #17 src/pocketmine/Server(2186): pocketmine\Server->tickProcessor()
[11:46:36] [Server thread/DEBUG]: #18 src/pocketmine/Server(1765): pocketmine\Server->start()
[11:46:36] [Server thread/DEBUG]: #19 src/pocketmine/PocketMine(250): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/Serveurs/Faction/, string /home/Serveurs/Faction/plugins/)
[11:46:36] [Server thread/DEBUG]: #20 (1): require(string phar:///home/Serveurs/Faction/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by UnknownOre** [comment] 2019-03-30 15:53
Duplicate of #10
download the plugin from  poggit ci https://poggit.pmmp.io/ci/UnknownOre/EnchantShopUI/EnchantShopUI

**Closed as completed** 2019-03-30 15:56 UTC
Labels: duplicate, invalid
