### ISSUE TITLE
Can you help me please!? 

### ISSUE THREAD

**Issue by ghost** [UnknownOre/EnchantShopUI#17] opened 2019-04-13 07:04 UTC
If i type /enchantui i will be kicked!
Console Error:
[Server thread/CRITICAL]: ErrorException: "Invalid argument supplied for foreach()" (EXCEPTION) in "plugins/EnchantUI.phar/src/UnknownOre/EnchantUI/Main" at line 79

**Comment by UnknownOre** [comment] 2019-04-13 18:22
can you show me your config file?

**Comment by ghost** [comment] 2019-04-14 06:28
Of Course: (its default config)
---
#Don't Change this
version: "0.5"

#send EnchantUI to the player when he interacts with the Enchanting-table
enchanting-table: true

#EnchantUI version 0.5
Title: "§cEnchantment Shop"
Button: "§3{NAME} §a{PRICE}$"
slider-title: "§5Level"
messages:
  thanks: "§athank you for using Enchantment Shop"
  label: "§eYou will pay {PRICE}$ per level"
  not-enough-money: "§cyou don't have enough money!"
  paid-success: "§aYou bought {NAME} level {LEVEL} for {PRICE}$"
  hold-item: "§cPlease hold an item that can be enchanted"
  no-perm: "§cYou don't have permission to use this command"
  incompatible-enchantment:
  
#WARNING: Use only Enchantment ID at incompatible-enchantments example [1,10,13]
shop:
- name: "Fire Protection"
  enchantment: fire_protection
  price: 100
  max-level: 2
  incompatible-enchantments: []
- name: "Protection"
  enchantment: 1
  price: 100
  max-level: 3
  incompatible-enchantments: []
...

**Comment by UnknownOre** [comment] 2019-04-18 08:47
i can't reproduce this issue i'll close it for now

**Closed as completed** 2019-04-21 21:34 UTC
Labels: bug, can't reproduce, not confirmed
